# Uncomment the next line to define a global platform for your project
target 'Keychain Installer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
        pod 'AHLaunchCtl'
  # Pods for Installer-Node
post_install do |installer|
                installer.pods_project.build_configurations.each do |config|
                        config.build_settings.delete('CODE_SIGNING_ALLOWED')
                        config.build_settings.delete('CODE_SIGNING_REQUIRED')
                end
        end

end
